// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'demo-api-key-web',
    appId: '1:123456789:web:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'aquareminder-demo',
    authDomain: 'aquareminder-demo.firebaseapp.com',
    storageBucket: 'aquareminder-demo.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgn35n9Fsb3Je3qp3trNp1A1jS2L3L9d4',
    appId: '1:850036774299:android:86d636b93cf4aea176fd3e',
    messagingSenderId: '850036774299',
    projectId: 'aqualert-7850d',
    storageBucket: 'aqualert-7850d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Q1N1C9tekb5eBfFQBEUbZ8tQiHtSSFE',
    appId: '1:850036774299:ios:aa12a9d2581c50da76fd3e',
    messagingSenderId: '850036774299',
    projectId: 'aqualert-7850d',
    storageBucket: 'aqualert-7850d.firebasestorage.app',
    androidClientId: '850036774299-9t116fu5rhf9iu3bjlf04jigd2vi09ij.apps.googleusercontent.com',
    iosClientId: '850036774299-7pr2tcmo7j053t4v3n0pocjlffhiac2d.apps.googleusercontent.com',
    iosBundleId: 'com.dlrackgz.aqualert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'demo-api-key-macos',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'aquareminder-demo',
    storageBucket: 'aquareminder-demo.appspot.com',
    androidClientId: '123456789-abcdef123456.apps.googleusercontent.com',
    iosClientId: '123456789-abcdef123456.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterReminder',
  );
}